concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    if: github.repository == 'apache/cloudstack'
    name: codecov
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK11
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build CloudStack with Quality Checks
      run: 'git clone https://github.com/shapeblue/cloudstack-nonoss.git nonoss

        cd nonoss && bash -x install-non-oss.sh && cd ..

        mvn -P quality -Dsimulator -Dnoredist clean install -T$(nproc)

        '
    - continue-on-error: true
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: ./client/target/site/jacoco-aggregate/jacoco.xml
        flags: unit-tests
        name: codecov
        verbose: true
name: Coverage Check
on:
  repository_dispatch:
    types: trigger-ga___codecov.yml
permissions:
  contents: read
