concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    if: github.repository == 'apache/cloudstack'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USER }}
    - continue-on-error: true
      name: Set Docker repository name
      run: echo "DOCKER_REPOSITORY=apache" >> $GITHUB_ENV
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set ACS version
      run: echo "ACS_VERSION=$(grep '<version>' pom.xml | head -2 | tail -1 | cut
        -d'>' -f2 |cut -d'<' -f1)" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set Docker image TAG
      run: echo "TAG=$(if [ "${{ github.ref_type }}" = "tag" ];then echo ${{ github.ref_name
        }}; elif [[ "${ACS_VERSION}" =~ .*-SNAPSHOT ]];then echo ${ACS_VERSION}-$(date
        +'%Y%m%d-%H%M%S');else echo ${ACS_VERSION};fi)" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set Docker image FULL TAG
      run: echo "FULL_TAG=$(if [ "${{ secrets.DOCKER_REGISTRY }}" = "" ];then echo
        ${DOCKER_REPOSITORY}/cloudstack-simulator:${TAG};else echo ${{ secrets.DOCKER_REGISTRY
        }}/${DOCKER_REPOSITORY}/cloudstack-simulator:${TAG};fi)" >> $GITHUB_ENV
    - continue-on-error: true
      name: Build the Docker image for cloudstack-simulator
      run: cd tools/docker && docker build ../.. --file Dockerfile --tag ${FULL_TAG}
    - continue-on-error: true
      name: Push Docker image to Docker Registry
      run: docker push ${FULL_TAG}
name: Docker Image Build
on:
  repository_dispatch:
    types: trigger-ga___docker-cloudstack-simulator.yml
permissions:
  contents: read
