concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check Out
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install
      run: 'python -m pip install --upgrade pip

        pip install pre-commit

        '
    - continue-on-error: true
      name: Set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
        path: ~/.cache/pre-commit
    - continue-on-error: true
      name: Run pre-commit
      run: pre-commit run --all-files
name: Lint
on:
  repository_dispatch:
    types: trigger-ga___linter.yml
permissions:
  contents: read
