jobs:
  build:
    if: github.repository == 'apache/cloudstack'
    name: Main Sonar JaCoCo Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK11
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-m2

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Run Tests with Coverage
      run: 'git clone https://github.com/shapeblue/cloudstack-nonoss.git nonoss

        cd nonoss && bash -x install-non-oss.sh && cd ..

        mvn -T$(nproc) -P quality -Dsimulator -Dnoredist clean install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.projectKey=apache_cloudstack

        '
name: Main Branch Sonar Quality Check
on:
  repository_dispatch:
    types: trigger-ga___main-sonar-check.yml
permissions:
  contents: read
  pull-requests: write
