concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  triage:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Conflict Check
      uses: eps1lon/actions-label-merge-conflict@v2.0.0
      with:
        commentOnDirty: This pull request has merge conflicts. Dear author, please
          fix the conflicts and sync your branch with the base branch.
        continueOnMissingPermissions: true
        dirtyLabel: status:has-conflicts
        removeOnDirtyLabel: status:ready-for-review
        repoToken: ${{ secrets.GITHUB_TOKEN }}
name: PR Merge Conflict Check
on:
  repository_dispatch:
    types: trigger-ga___merge-conflict-checker.yml
permissions:
  contents: read
