concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    if: github.repository == 'apache/cloudstack' && github.event.pull_request.head.repo.full_name
      == github.repository
    name: Sonar JaCoCo Coverage
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: refs/pull/${{ github.event.number }}/merge
    - continue-on-error: true
      name: Set up JDK11
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-m2

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEADREF: ${{ github.event.pull_request.head.ref }}
        PR_ID: ${{ github.event.pull_request.number }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      id: coverage
      name: Run Build and Tests with Coverage
      run: 'git clone https://github.com/shapeblue/cloudstack-nonoss.git nonoss

        cd nonoss && bash -x install-non-oss.sh && cd ..

        mvn -T$(nproc) -P quality -Dsimulator -Dnoredist clean install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.projectKey=apache_cloudstack -Dsonar.pullrequest.key="$PR_ID" -Dsonar.pullrequest.branch="$HEADREF"
        -Dsonar.pullrequest.github.repository=apache/cloudstack -Dsonar.pullrequest.provider=GitHub
        -Dsonar.pullrequest.github.summary_comment=true

        '
name: Sonar Quality Check
on:
  repository_dispatch:
    types: trigger-ga___sonar-check.yml
permissions:
  contents: read
  pull-requests: write
