concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - continue-on-error: true
      name: Env details
      run: 'uname -a

        whoami

        free -m

        nproc

        npm version

        '
    - continue-on-error: true
      name: Build UI
      run: 'cd ui

        sudo npm install -g @vue/cli npm-check-updates

        npm install

        npm run build

        npm run lint

        npm run test:unit

        '
    - continue-on-error: true
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: ./coverage/lcov.info
        flags: uitests
        name: codecov
        verbose: true
        working-directory: ui
name: UI Build
on:
  repository_dispatch:
    types: trigger-ga___ui.yml
permissions:
  contents: read
